name: Demo Setup

on:
  push:
    branches:
      - deva

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Demo
        uses: actions/checkout@v3
      - name: tets
        run : echo "Hello my secret is $SECRET" 
    
    env:
      SECRET: ${{secrets.SECRET}}