name: Secret Demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - name: Get the code
          uses: actions/checkout@v3

        - name: Print environment Secret
          run : echo "Hello my ecret is $Secret"
          env:
            Secret : ${{ secrets.Secret }}