name: Secret Demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - name: Get the code
          uses: actions/checkout@v3

        - name: Print environment Secret
          run : echo "Hello my ecret is $Secret"

        - name: Another secret
          run : echo " Hey my is your $MY_SECRET"
          env : 
            Secret :    ${{ secrets.Secret }}
            MY_SECRET : ${{ secrets.MY_SECRET }}

            