name: Secret Demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Get the code
          uses: actions/checkout@v3

        - name: Print Secret
          run: echo "Hello my secret is $MY_SECRET"
          env:
            MY_SECRET : ${{ secrets.MY_SECRET}}
        
        - name: Another Secret
          run : echo " Ronaldo is the $SECRET"
          env:
            SECRET: ${{secrets.SECRET}}
