name: Secret Demo
on: 
    push:
      branches:
        - main
jobs:
  test:
    runs-on : ubuntu-latest
    steps:
      - name:  Get the code
        uses:  actions/checkout@v3
      - name : Demo
        run :  echo " Hello my password is $SECRET"
    
    env:
      SECRET : ${{secrets.SECRET}}